DROP TABLE BANKCODE;
DROP TABLE BANKMEMBER;
DROP TABLE BANKTEAM;
DROP TABLE DHISTORY;

CREATE TABLE BANKCODE(
    CCODE       NUMBER PRIMARY KEY,
    CNAME       NVARCHAR2(10)
);
INSERT INTO BANKCODE VALUES(1, '예금');
INSERT INTO BANKCODE VALUES(2,'적금');
INSERT INTO BANKCODE VALUES(3,'청약');
INSERT INTO BANKCODE VALUES(4,'주식');
select * from bankcode;

CREATE TABLE BANKMEMBER(
    MID         NVARCHAR2(20) PRIMARY KEY,
    MPASSWORD   NVARCHAR2(16),
    MNAME       NVARCHAR2(5),
    MPHONE      NVARCHAR2(14)
);
select * from bankmember;

CREATE TABLE BANKTEAM(
    MID         NVARCHAR2(20) CONSTRAINT BT_BM_FK REFERENCES BANKMEMBER,
    TACCOUNT    NVARCHAR2(20) PRIMARY KEY,
    TBALANCE    NUMBER,
    CCODE       NUMBER CONSTRAINT BT_BC_FK REFERENCES BANKCODE
);
ALTER TABLE BANKTEAM ADD TNAME NVARCHAR2(20);
select * from bankteam;
INSERT INTO BANKTEAM VALUES ('ADMIN',110-456-456789,0,1,'asdf');
ALTER TABLE BANKTEAM drop column TNAME;
DELETE FROM BANKTEAM;
COMMIT;

UPDATE BANKTEAM
SET TBALANCE = 4200000 WHERE MID = 'ADMIN';


select * from bankteam;
SELECT * FROM BANKTEAM WHERE tAccount= '110-070-625481';
SELECT * FROM BANKTEAM;
 
CREATE TABLE DHISTORY(
    HDATE     DATE,
    TACCOUNT  NVARCHAR2(20) CONSTRAINT HI_BT_FK REFERENCES BANKTEAM,
    HHIS      NVARCHAR2(4),
    HMOMEY    NUMBER
);
CREATE TABLE PACCOUNT(
    TACCOUNT    NVARCHAR2(20) CONSTRAINT AT_TT_FK REFERENCES BANKTEAM,
    ATOTAL      NUMBER,         -- 합계
    ACOUNT      NUMBER          -- 내역갯수
);
CREATE TABLE BANKRECORD(
    RNUM        NUMBER UNIQUE,
    RDATE       DATE,
    TACCOUNT    NVARCHAR2(20) CONSTRAINT BR_BT_FK REFERENCES BANKTEAM,
    TBALANCE    NUMBER,
    RCHECK      NVARCHAR2(10)    
);

select * from dhistory;
select *from bankteam;
select *from bankmember;
select *from bankcode;
SELECT * FROM BANKRECORD;
delete from BANKRECORD;
SELECT * FROM PACCOUNT;
commit;
DELETE FROM PACCOUNT;
SELECT HDATE, TACCOUNT, HHIS, HMOMEY FROM DHISTORY WHERE TACCOUNT = '110-524-761018';

-----------------------------------------------------------------------------------------------
-- 팀프로 젝트 항공사 예약 프로그램 만들기

--테이블 드랍 순서
DROP TABLE COMPANYRECOMMEND;
DROP TABLE CITYRECOMMEND;
DROP TABLE ARESERVATION;
DROP TABLE ASCHEDULE;
DROP TABLE AIRLINE;
dROP TABLE PAY;
DROP TABLE CODE;
DROP TABLE AMEMBER;


CREATE TABLE AMEMBER(
    MID         NVARCHAR2(20) PRIMARY KEY,
    MPW         NVARCHAR2(20),
    MNAME       NVARCHAR2(5),
    MPHONE      NVARCHAR2(13),
    MPASSPORT   NVARCHAR2(9),
    MBIRTH      DATE,
    MADMIN      NUMBER
);

CREATE TABLE CODE(
    CODE        NVARCHAR2(5) PRIMARY KEY,
    NATION      NVARCHAR2(20),
    CITY        NVARCHAR2(20),
    TZONE       NUMBER
);

CREATE TABLE PAY(
    RCHECK      NUMBER PRIMARY KEY,
    PNAME       NVARCHAR2(10)
);

INSERT INTO PAY VALUES(0,'장바구니');
INSERT INTO PAY VALUES(1,'결제대기');
INSERT INTO PAY VALUES(2,'결제완료');

CREATE  TABLE AIRLINE(
    ANAME       NVARCHAR2(10) PRIMARY KEY,
    ATYPE       NVARCHAR2(10),
    ACOMPANY    NVARCHAR2(20),
    ATIME       NUMBER,
    DCODE       NVARCHAR2(3) CONSTRAINT AD_CC_FK REFERENCES CODE(CODE),
    ACODE       NVARCHAR2(3) CONSTRAINT AA_CC_FK REFERENCES CODE(CODE)
);



CREATE TABLE ASCHEDULE(
    SNUM        NVARCHAR2(20) PRIMARY KEY,
    SSTART      NVARCHAR2(20),
    SPRICE      NUMBER,
    ANAME       NVARCHAR2(10) CONSTRAINT SN_AN_FK REFERENCES AIRLINE
);


CREATE TABLE ARESERVATION(
    MID         NVARCHAR2(20) CONSTRAINT RI_MI_FK REFERENCES AMEMBER,
    RTIME       DATE,
    SNUM        NVARCHAR2(20)  CONSTRAINT RN_SN_FK REFERENCES ASCHEDULE,
    RNUM        NUMBER,
    RCHECK      NUMBER NULL CONSTRAINT PR_RR_FK REFERENCES PAY
);
ALTER TABLE ARESERVATION
ADD CONSTRAINT RE_RNUM PRIMARY KEY (RNUM);

-- 추천여행지 조회 테이블
CREATE TABLE CITYRECOMMEND(
    CITY        NVARCHAR2(20) CONSTRAINT RC_CC_FK REFERENCES CODE,
    TOURIST     NVARCHAR2(100),         --관광지
    REXCHANGE   NVARCHAR2(20),          -- 환율
    RFOOD       NVARCHAR2(20)           -- 유명한 음식
);

-- 추천항공사 조회 테이블
CREATE TABLE COMPANYRECOMMEND(
    ANAME       NVARCHAR2(10) CONSTRAINT RN_AN_FK REFERENCES AIRLINE,
    CROUNGE     NVARCHAR2(50),          -- 라운지 정보
    COMPANYURL  NVARCHAR2(50)           -- 항공사 홈페이지
);
COMMIT;

SELECT * FROM AMEMBER;
SELECT * FROM AIRLINE;
SELECT * FROM CODE;
SELECT * FROM ASCHEDULE;
SELECT * FROM ARESERVATION;
delete from areservation;

COMMIT;